title: Siddharth Holankar
logo: /assets/IMG_1736676340698.jpeg
description: Aspiring Business Analyst | Former Data Analyst at Morningstar | Transforming Data Into Strategic Decisions
show_downloads: false
theme: jekyll-theme-minimal


