title: Siddharth Holankar
logo: "/assets/profile.jpeg"
description: Aspiring Business Analyst | Former Data Analyst at Morningstar | Transforming Data Into Strategic Decisions
show_downloads: false

# Theme Settings
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0

# Custom CSS
plugins:
  - jekyll-remote-theme

# Exclude unnecessary files
exclude:
  - README.md
  - .nojekyll
