title: Siddharth Holankar
#logo: /assets/img/headshot_circle.png
#description: Aspiring Business Analyst | Former Data Analyst at Morningstar | Transforming Data Into Strategic Decisions
#show_downloads: false
theme: jekyll-theme-minimal
